Update targetcalle.yml

diff --git a/.github/workflows/targetcalle.yml b/.github/workflows/targetcalle.yml
--- a/.github/workflows/targetcalle.yml
+++ b/.github/workflows/targetcalle.yml
@@ -21,6 +21,12 @@ jobs:
         run: |
           echo "automationsuccess"
           echo "XRunId10Y"
-         
+          splitRunIdWithDate = ''
+          if [ -n "${splitRunIdWithDate}" ]; then
+          echo "pass"
+          else
+          echo "fail"
+          exit 1 
+          fi
                  
     
